// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tarea4.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Canton", b =>
                {
                    b.Property<int>("CantonPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CantonNombre");

                    b.Property<int>("ProvinciaFK")
                        .HasColumnType("INTEGER");

                    b.HasKey("CantonPK");

                    b.HasIndex("ProvinciaFK");

                    b.ToTable("Cantones");
                });

            modelBuilder.Entity("Distrito", b =>
                {
                    b.Property<int>("DistritoPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantonFK")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DistritoNombre");

                    b.HasKey("DistritoPK");

                    b.HasIndex("CantonFK");

                    b.ToTable("Distritos");
                });

            modelBuilder.Entity("Provincia", b =>
                {
                    b.Property<int>("ProvinciaPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ProvinciaNombre");

                    b.HasKey("ProvinciaPK");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Canton", b =>
                {
                    b.HasOne("Provincia", "Provincia")
                        .WithMany("Cantones")
                        .HasForeignKey("ProvinciaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Distrito", b =>
                {
                    b.HasOne("Canton", "Canton")
                        .WithMany("Distritos")
                        .HasForeignKey("CantonFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("Canton", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("Provincia", b =>
                {
                    b.Navigation("Cantones");
                });
#pragma warning restore 612, 618
        }
    }
}
